service: aws-node-web-scrapping-lambda
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: index.handler
    url: true
    timeout: 30
    memorySize: 768
    # events:
    #   - schedule: rate(1 hour)
    #   - schedule: cron(0 12 * * ? *)
